sudo: required

language: python
python:
  - "3.5"

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/f32286c047612bea82b0
    on_success: always  # options: [always|never|change] default: change
    on_failure: always  # options: [always|never|change] default: always
    on_start: never    # options: [always|never|change] default: never

services:
  - docker

addons:
  sauce_connect:
    username: "dogi"
  jwt:
    secure: "Eg5bJUkapZCqG6F5i4xnjsFyJnNNxqgT3cvKwNsh2MZ5ciB1Q7HmK4vJMTS0G3qgu6Q3B4IElZsYcmlerwOQWZNkeDHGCf6HhDedzkObmQn42e9yZxjF8RtBNnifbHx/28n5DczpcUskIjg6WrC2djsZl4iPJYH3hjjMlftcNfGnrlinjQU8kChgfeiP0qXRUr0qnA4ivlNCzWjKVhBs/hopfF5CvE80HS7kefW31/51xzkZ91JzYMO1nl1iPN2/LFEkHO1kn17ktVKbb4OyZuYApV3NK5j2qaTuZVzlKpk6zuy6YdY9UK8xuS09FmpVa8q+8p9HAD3d2mGzNksTP/rNNp+K75ieSqc4xBDvygyWZj75oEatUFV0j1hshVOZHk/pievgsIH+2pBIrwBY8Uq3X5TGeA7X3yesqQ3aHjykemy8l3HuQXOX2qALbLen7LBYf+xsJVw4uX0a9LjHLve8GH7Cyal6Ih9YRIMFti3y/1cYzK4/NAMi9xXnF6fSh5eIySmK08XL/8WuiquPPcQLqnVhCFG4Vbk6/LNjzzTr2xzDOKf2EfMrlXyimThdysPM+HsNTjHwBIdqWbhap+XSCPURlFbcGpm/lyHkHU/M2Yy8UHwjec/Vyl/l/MHIseGOiOM0L3aZ2SVF+S9bsGeMgy28awzS9nd56BWqKTM="
    #dogirepo secure: "dhXRocGdvpkAhjra2oJ+l+AzgdN+QCuVq0RHv7KGF3kaK6bmx/QMjkwDho7ZQ0ndR6TQ52qUkracVIVTDm+81ZiWjTdAP0QwWCITLaqB+KapgrEx7nMldjEzTDSj1rnQ4KmE+k0G3wbvjSGgD7V0JOBQTi1lKmwaI7kMmyhNBvM5KRhrrWx9oTFs99nx84XeEF3XayEix6eDTkxStc/RILLTMBJop9iAiTzpkXuwc5F+xs/PQXJ/lqhZyp5arihJvUCRPhpXgzrfc+LQJUMGVd7DHsv49BZPDSZ5y4D5r5u27AtAhTQiqM+ozvWWxvGi7ju5CW1wiLxBKDbjhbbCYaZdKH6kxoFGofJuswrGygUfaqVBg/tz0DxLKGMiNYedfJcNMBzOyXjEKzS52BdzLqZZmRj1JekaVHw1P6vkkCTU/512JMJZmlSE8LsROyMtIq8Vraz++gmYShNePtA4afVNckpnY8uvusWT/0f+td9K1yH7El4rMxO5j30q55K9nTDqE3R/GwgX4vxhdMJ//KeYgGTg9e/QlE9sUZad0GdaZmRr5iajqzXFAS9bQpLvyyRC4LviBEpXGkZhiicpbqIvYl6K+fvxl5/GhfQfIr0c35vlNMKcOUpr7zwySGch+mVo/pmXefKtaDDCGKdNJIW9qHY29JkBXrJBrfILnQ8="
    #travis encrypt SAUCE_ACCESS_KEY=...
install:
  - pip install selenium
  - pip install sauceclient

before_install:
  - docker pull klaemo/couchdb:1.6.1
  - docker run -d -p 5981:5984 --name bell klaemo/couchdb:1.6.1
  - echo "node_modules/.bin/couchapp push \$1 \$2" > pushDocToDb.sh
  - chmod +x node_modules/.bin/couchapp pushDocToDb.sh
  - cp install_windows install_linux
  - sed -i "s#pushDocToDb.bat#./pushDocToDb.sh#" install_linux
  - sed -i 's#databases\\\\\\\\#databases/#' install_linux
  - sed -i 's#databases\\\\\\#databases/#' install_linux
  - sed -i 's#databases\\\\#databases/#' install_linux
  - sed -i 's/NationBell/nation/' init_docs/ConfigurationsDoc-Nation.txt
  - sed -i 's/nationbell/NATION/' init_docs/ConfigurationsDoc-Nation.txt
  - sed -i 's#Male#Female#' install_linux
  - sed -i 's#somalia#nation#' install_linux
  - while ! curl -X GET http://127.0.0.1:5981/_all_dbs ; do sleep 1; done
  - node install_linux http://127.0.0.1:5981
  - curl -X PUT 'http://127.0.0.1:5981/_config/log/file' -d '"/usr/local/var/log/couchdb/couch.log"'
  - curl -X PUT 'http://127.0.0.1:5981/_config/httpd/allow_jsonp' -d '"true"'
  - curl -X PUT 'http://127.0.0.1:5981/_config/admins/nation' -d '"oleoleole"'

script:
  - export
  - docker ps -a | grep bell
  - curl -X GET http://127.0.0.1:5981/_all_dbs
  - i=$(curl -X GET http://127.0.0.1:5981/_all_dbs | jq length); if [ $i -ne 38 ]; then exit 1; fi
  - python -m unittest discover tests
